---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflow.secret.name" . }}
  namespace: {{ include "cloudflow.namespace" . }}
  labels:
    {{- include "cloudflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  CLOUD_FLOW_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhousePassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
