{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflow.serviceAccountName" . }}
  namespace: {{ include "cloudflow.namespace" . }}
  labels:
    {{- include "cloudflow.labels" . | nindent 4 }}
{{- end }}
