apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflow-agent
  namespace: cloudflow
  labels:
    app: cloudflow-agent
    component: agent
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflow-agent-token
  namespace: cloudflow
  annotations:
    kubernetes.io/service-account.name: cloudflow-agent
type: kubernetes.io/service-account-token
