// Cloud Flow Server — PM2 进程管理配置
module.exports = {
  apps: [
    {
      name: "cloud-flow-center",
      script: "./bin/cloud-flow-center",
      cwd: __dirname,
      env: {
        DATA_DIR: "./data",
      },
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      out_file: "./logs/center-out.log",
      error_file: "./logs/center-error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "cloud-flow-edge",
      script: "./bin/cloud-flow-edge",
      cwd: __dirname,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      out_file: "./logs/edge-out.log",
      error_file: "./logs/edge-error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "cloud-flow-portal",
      script: "./bin/cloud-flow-portal",
      cwd: __dirname,
      env: {
        PORT: "8080",
        DATA_DIR: "./data",
      },
      max_memory_restart: "256M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      out_file: "./logs/portal-out.log",
      error_file: "./logs/portal-error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
    {
      name: "cloud-flow-mixserver",
      script: "./bin/cloud-flow-mixserver",
      cwd: __dirname,
      env: {
        PORT: "8081",
        DATA_DIR: "./data",
      },
      max_memory_restart: "256M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      out_file: "./logs/mixserver-out.log",
      error_file: "./logs/mixserver-error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
    },
  ],
};
